### ISSUE TITLE
ReferenceError: Can't find variable: fetch

### ISSUE THREAD

**Issue by jesperlandberg** [Anthodpnt/Highway#3]
ReferenceError: Can't find variable: fetch

Hi, getting this error in Safari. Works fine in Chrome and Firefox.

**Comment by Anthodpnt** [comment]
Hi @jesperlandberg,

I don't know which version of Safari you're using but Highway is using the [Fetch API](https://developer.mozilla.org/en/docs/Web/API/Fetch_API).
Maybe your version of Safari doesn't support this API and you need to install a polyfill like [whatwg-fetch](https://www.npmjs.com/package/whatwg-fetch) that will solve your problem.

Best regards,
Anthodpnt
